/*
 * Created by Mark Durlinger. MIT License.
 * 50% human, 50% AI, 100% chaos.
 */

/**
 * Setup orchestrator - manages the 5-step onboarding flow.
 * Shows a disclaimer screen before the wizard begins.
 */

import { h, render, clear } from '../../core/dom.js';
import { icon } from '../../ui/icon.js';
import { renderWelcome } from './step-welcome.js';
import { renderAccount } from './step-account.js';
import { renderProvider } from './step-provider.js';
import { renderSite } from './step-site.js';
import { renderLaunching } from './step-launching.js';

const STEPS = [
  { id: 'welcome', label: 'Welcome' },
  { id: 'account', label: 'Account' },
  { id: 'provider', label: 'AI' },
  { id: 'site', label: 'Project' },
  { id: 'launching', label: 'Launch' },
];

/**
 * Render the setup wizard.
 */
export function renderSetup(container) {
  let currentStep = 0;
  const setupData = {
    displayName: '',
    username: '',
    password: '',
    providerId: 0,
    providerName: '',
    modelId: '',
    apiKey: '',
    siteName: '',
    siteDomain: '',
    siteDescription: '',
  };

  const wrapper = h('div', { className: 'setup-container' });
  render(container, wrapper);

  // Show disclaimer first, then start wizard on accept
  showDisclaimer(wrapper, () => renderStep());

  function renderStep() {
    clear(wrapper);

    // Create labeled stepper
    const stepperItems = [];
    STEPS.forEach((step, i) => {
      if (i > 0) {
        stepperItems.push(h('div', {
          className: `setup-stepper__line${i <= currentStep ? ' done' : ''}`,
        }));
      }
      const state = i < currentStep ? 'done' : i === currentStep ? 'active' : '';
      const circleContent = i < currentStep ? '\u2713' : String(i + 1);
      stepperItems.push(h('div', { className: `setup-stepper__item ${state}` }, [
        h('div', { className: 'setup-stepper__circle' }, circleContent),
        h('div', { className: 'setup-stepper__label' }, step.label),
      ]));
    });
    const progress = h('div', { className: 'setup-stepper' }, stepperItems);

    const card = h('div', { className: 'setup-card' }, [progress]);
    wrapper.appendChild(card);

    const stepContainer = h('div');
    card.appendChild(stepContainer);

    function next() {
      currentStep++;
      if (currentStep < STEPS.length) {
        renderStep();
      }
    }

    const stepId = STEPS[currentStep].id;
    switch (stepId) {
      case 'welcome':
        renderWelcome(stepContainer, setupData, next);
        break;
      case 'account':
        renderAccount(stepContainer, setupData, next);
        break;
      case 'provider':
        renderProvider(stepContainer, setupData, next);
        break;
      case 'site':
        renderSite(stepContainer, setupData, next);
        break;
      case 'launching':
        renderLaunching(stepContainer, setupData);
        break;
    }
  }
}

/**
 * Disclaimer pre-screen — must accept to proceed.
 */
function showDisclaimer(wrapper, onAccept) {
  clear(wrapper);

  const acceptBtn = h('button', {
    className: 'btn btn--primary btn--lg',
    onClick: onAccept,
  }, 'I understand, let\u2019s go');

  const card = h('div', { className: 'setup-card' }, [
    h('div', { className: 'setup-card__header' }, [
      h('img', { src: '/ho_white.svg', className: 'setup-logo', alt: 'HO' }),
      h('h2', { className: 'setup-card__title' }, 'Before we begin'),
      h('p', { className: 'setup-card__desc' }, 'A few things to keep in mind:'),
    ]),
    h('ul', { className: 'setup-disclaimer' }, [
      h('li', {}, 'This software is still experimental, built for testing and tinkering.'),
      h('li', {}, 'You are responsible for any content generated by HO.'),
      h('li', {}, 'No warranty, no guarantees.'),
      h('li', {}, 'Created by Mark Durlinger (Markyboy).'),
      h('li', {}, 'Licensed under MIT.'),
    ]),
    h('div', { className: 'setup-actions' }, [
      h('button', {
        className: 'btn btn--ghost',
        onClick: () => { window.location.reload(); },
      }, 'Decline'),
      acceptBtn,
    ]),
  ]);

  wrapper.appendChild(card);

  // Enter to accept
  function onKey(e) {
    if (e.key === 'Enter') {
      e.preventDefault();
      document.removeEventListener('keydown', onKey);
      onAccept();
    }
  }
  document.addEventListener('keydown', onKey);
  acceptBtn.focus();
}
